//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olsens.Plugins.StatusQueryService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bdm.nsw.gov.au/Schemas/CommonTypes_v1.0")]
    public partial class Fault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private string[] errorDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ErrorDetail", Order=2)]
        public string[] ErrorDetail {
            get {
                return this.errorDetailField;
            }
            set {
                this.errorDetailField = value;
                this.RaisePropertyChanged("ErrorDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bdm.nsw.gov.au/Schemas/StatusQuery_v1.0")]
    public partial class StatusQueryResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string notificationIDField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NotificationID {
            get {
                return this.notificationIDField;
            }
            set {
                this.notificationIDField = value;
                this.RaisePropertyChanged("NotificationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bdm.nsw.gov.au/Schemas/StatusQuery_v1.0")]
    public partial class StatusQueryRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string notificationIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NotificationID {
            get {
                return this.notificationIDField;
            }
            set {
                this.notificationIDField = value;
                this.RaisePropertyChanged("NotificationID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bdm.nsw.gov.au/Schemas/StatusQueryService_v1.0", ConfigurationName="StatusQueryService.StatusQueryPortType")]
    public interface StatusQueryPortType {
        
        // CODEGEN: Generating message contract since the operation StatusQuery is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/StatusQuery", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Olsens.Plugins.StatusQueryService.Fault), Action="/StatusQuery", Name="Fault", Namespace="http://bdm.nsw.gov.au/Schemas/CommonTypes_v1.0")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Olsens.Plugins.StatusQueryService.Response StatusQuery(Olsens.Plugins.StatusQueryService.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/StatusQuery", ReplyAction="*")]
        System.Threading.Tasks.Task<Olsens.Plugins.StatusQueryService.Response> StatusQueryAsync(Olsens.Plugins.StatusQueryService.Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bdm.nsw.gov.au/Schemas/StatusQuery_v1.0", Order=0)]
        public Olsens.Plugins.StatusQueryService.StatusQueryRequestType StatusQueryRequest;
        
        public Request() {
        }
        
        public Request(Olsens.Plugins.StatusQueryService.StatusQueryRequestType StatusQueryRequest) {
            this.StatusQueryRequest = StatusQueryRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bdm.nsw.gov.au/Schemas/StatusQuery_v1.0", Order=0)]
        public Olsens.Plugins.StatusQueryService.StatusQueryResponseType StatusQueryResponse;
        
        public Response() {
        }
        
        public Response(Olsens.Plugins.StatusQueryService.StatusQueryResponseType StatusQueryResponse) {
            this.StatusQueryResponse = StatusQueryResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StatusQueryPortTypeChannel : Olsens.Plugins.StatusQueryService.StatusQueryPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StatusQueryPortTypeClient : System.ServiceModel.ClientBase<Olsens.Plugins.StatusQueryService.StatusQueryPortType>, Olsens.Plugins.StatusQueryService.StatusQueryPortType {
        
        public StatusQueryPortTypeClient() {
        }
        
        public StatusQueryPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StatusQueryPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatusQueryPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatusQueryPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Olsens.Plugins.StatusQueryService.Response Olsens.Plugins.StatusQueryService.StatusQueryPortType.StatusQuery(Olsens.Plugins.StatusQueryService.Request request) {
            return base.Channel.StatusQuery(request);
        }
        
        public Olsens.Plugins.StatusQueryService.StatusQueryResponseType StatusQuery(Olsens.Plugins.StatusQueryService.StatusQueryRequestType StatusQueryRequest) {
            Olsens.Plugins.StatusQueryService.Request inValue = new Olsens.Plugins.StatusQueryService.Request();
            inValue.StatusQueryRequest = StatusQueryRequest;
            Olsens.Plugins.StatusQueryService.Response retVal = ((Olsens.Plugins.StatusQueryService.StatusQueryPortType)(this)).StatusQuery(inValue);
            return retVal.StatusQueryResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Olsens.Plugins.StatusQueryService.Response> Olsens.Plugins.StatusQueryService.StatusQueryPortType.StatusQueryAsync(Olsens.Plugins.StatusQueryService.Request request) {
            return base.Channel.StatusQueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Olsens.Plugins.StatusQueryService.Response> StatusQueryAsync(Olsens.Plugins.StatusQueryService.StatusQueryRequestType StatusQueryRequest) {
            Olsens.Plugins.StatusQueryService.Request inValue = new Olsens.Plugins.StatusQueryService.Request();
            inValue.StatusQueryRequest = StatusQueryRequest;
            return ((Olsens.Plugins.StatusQueryService.StatusQueryPortType)(this)).StatusQueryAsync(inValue);
        }
    }
}
